spring:
  profiles:
    active: dev
    include:
      - swagger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/backendchallenge?createDatabaseIfNotExist=true;
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.hbm2ddl.auto: update
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  mail:
    host: localhost
    port: 25
    username:
    password:
  flyway:
    enabled: false
    url: jdbc:postgresql://127.0.0.1:5432/backendchallenge
    user: postgres
    password: postgres
    locations: classpath:/db
    baselineOnMigrate: true
    schemas: backendchallenge


server:
  port: 8080